### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikebevz.upnp/com.mikebevz.upnp.activities.MainActivity}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mikebevz** [mikebevz/UPnPBrowser#1]
Country IT
Phone   Transformer TF101
OS  3.2
App Version 1.1.1
wifi_on true
appname com.mikebevz.upnp
mobile_net_on   false
gps_on  not available [permissions]
screen_dpi(x:y) 160.15764:160.0
screen:width    545
screen:orientation  normal
screen:height   320

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikebevz.upnp/com.mikebevz.upnp.activities.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1815)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1831)
at android.app.ActivityThread.access$500(ActivityThread.java:122)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1024)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:132)
at android.app.ActivityThread.main(ActivityThread.java:4123)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:491)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.cybergarage.upnp.ssdp.SSDPSearchResponseSocket.start(SSDPSearchResponseSocket.java:87)
at org.cybergarage.upnp.ssdp.SSDPSearchResponseSocketList.start(SSDPSearchResponseSocketList.java:129)
at org.cybergarage.upnp.ControlPoint.start(ControlPoint.java:861)
at org.cybergarage.upnp.ControlPoint.start(ControlPoint.java:897)
at com.mikebevz.upnp.DeviceListAdapter.startControlPoint(DeviceListAdapter.java:296)
at com.mikebevz.upnp.activities.StateControlPointStarted.setSettings(StateControlPointStarted.java:42)
at com.mikebevz.upnp.activities.MainActivity.setState(MainActivity.java:258)
at com.mikebevz.upnp.activities.MainActivity.onCreate(MainActivity.java:82)
at android.app.Activity.performCreate(Activity.java:4397)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1048)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1779)
... 11 more

**Comment by Kooaal** [comment]
Hey,
I have the exact same problem with the clink210.jar.
I'm making an android controller, I can run once my controlPoint.start then the second time  I have this problem:
Caused by: java.lang.NullPointerException
at org.cybergarage.upnp.ssdp.SSDPSearchResponseSocket.start(SSDPSearchResponseSocket.java:87)

Did you find a solution to solve this problem ?
